# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# calcPhone.py
# Created on: 2018-06-08 10:01:41.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: This script will convernt a Telephone of a shapefile from
#              xxx-xxx-xxxx format to +1-xxx-xxx-xxxx
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

print "Beginning Converting Telephone"

# Local variables (path for shapefile):
shp = "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\Library_Pt.shp"

# Process: Add new Phone Field
arcpy.AddField_management(shp, "phone", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Phone Field
arcpy.CalculateField_management(shp, "phone", "\"+1-\" + !TELEPHONE!", "PYTHON_9.3", "")

# Process: Delete Original Telephone Field
arcpy.DeleteField_management(shp, "TELEPHONE")

print "Telephone Converted"
