# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# fishnet.py
# Created on: 2018-06-14 09:54:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Set Geoprocessing environments
arcpy.env.overwriteOutput = True

# Local variables:
fishnet_shp = "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\fishnet.shp"
County_shp = "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\Projected\\County.shp"
fishnet_Clip1 = "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\fishnet_county.shp"
fishnet_label_shp = "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\fishnet_label.shp"
Delete_succeeded = "false"

# Process: Create Fishnet
arcpy.CreateFishnet_management(fishnet_shp, "-77.0829926717009 38.53601686101", "-77.0829926717009 48.53601686101", "", "", "50", "40", "-76.6693325036584 39.1319863311607", "LABELS", "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\Projected\\County.shp", "POLYGON")

# Process: Clip
arcpy.Clip_analysis(fishnet_shp, County_shp, fishnet_Clip1, "")

# Process: Delete
arcpy.Delete_management(fishnet_label_shp, "")
arcpy.Delete_management(fishnet_shp, "")
