# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# reproject.py
# Created on: 2018-06-14 08:57:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Set Environment Variables
arcpy.env.workspace = "C:\Users\Gregory.mulea\Documents\ArcGIS\Workspace"
arcpy.env.overwriteOutput = True
outWorkspace = "C:\Users\Gregory.mulea\Documents\ArcGIS\Workspace\Projected"

for infc in arcpy.ListFeatureClasses():
    dsc = arcpy.Describe(infc)
    if dsc.spatialReference.Name == "Unkown":
        print ("Skipped this fc due to undefined coordinate system: " + infc)
    else:
        outfc = os.path.join(outWorkspace, infc)
        outCS = arcpy.SpatialReference('WGS 1984')
        arcpy.Project_management(infc, outfc, outCS)
        print(arcpy.GetMessages())
