# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# splitAddr.py
# Created on: 2018-06-08 09:48:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: This script will take an address field from an ArcMap shapefile
#              and split it into two fields, House Number and Street Name
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables (path for shapefile):
shp = "C:\\Users\\Gregory.mulea\\Documents\\ArcGIS\\Workspace\\Projected\\Library_Pt.shp"

# Process: Add Housenumber Field
arcpy.AddField_management(shp, "NUMBER", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Housenumber Field
arcpy.CalculateField_management(shp, "NUMBER", "!ADDRESS!.split(\" \")[0]", "PYTHON_9.3", "")

# Process: Add Street Field
arcpy.AddField_management(shp, "STREET", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Street Field
arcpy.CalculateField_management(shp, "STREET", "!ADDRESS!.split(\" \", 1)[1]", "PYTHON_9.3", "")

# Process: Delete Original Address Field
arcpy.DeleteField_management(shp, "ADDRESS")
